apiVersion: v1
description: IBM Operational Decision Manager for Developers
name: ibm-odm-dev
version: 1.0.0
appVersion: 8.9.2
home: https://developer.ibm.com/odm/
icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/odmicon.png
keywords:
- OperationalDecisionManager
- businessrules
maintainers:
- name: ODMDev
tillerVersion: ">=2.4.0"
