apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-shop4info-solr
  labels:
     app: {{ template "fullname" . }}-shop4info-solr
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}" 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-shop4info-solr
      annotations:
        productName: "IBM InfoSphere Information Server for Evaluation v11.7"
        productID: "IBMInfoSphereInformationServerForEvaluationv11.7_117_EVALUATION_00000"
        productVersion: "11.7"
    spec:
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      containers:
        - name: shop4info-solr
          image: {{ .Values.release.image.repository }}/iisee-eval-shop4info-solr:{{ .Values.release.image.tag }}
          imagePullPolicy: {{ .Values.release.image.pullPolicy }} 
          ports:
            - containerPort: 8983
          env:
            - name: SOLR_ZOOKEEPER_CONNECT
              value: {{ .Release.Name }}-zookeeper:2181/{{ .Release.Name }}-shop4info-solr
            - name: SOLR_ADVERTISED_HOST
              value: {{ .Release.Name }}-shop4info-solr
          volumeMounts:
            - mountPath: /opt/solr/server/solr
              name: solr-pv-volume
            - name: config-volume
              mountPath: /shop4info-solr/solr.xml
              subPath: solr.xml
            - name: config-volume
              mountPath: /opt/solr/server/resources/log4j.properties
              subPath: log4j.properties
      volumes:
        - name: solr-pv-volume
          persistentVolumeClaim:
           {{- if .Values.shop4infoSolr.volumeClaim.existingClaimName }}
            claimName: {{ .Values.shop4infoSolr.volumeClaim.existingClaimName }}
           {{- else }} 
            claimName: {{ .Release.Name }}-{{ .Values.shop4infoSolr.volumeClaim.name }} 
           {{- end }} 
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-solr
