# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "collectdexporter.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: collectdexporter
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "collectdexporter.fullname" . }}
spec:
  ports:
  - name: metrics
    targetPort: 9103
    port: {{ .Values.collectdExporter.service.serviceMetricsPort }}
    protocol: TCP
  - name: collector
    targetPort: 25826
    port: {{ .Values.collectdExporter.service.serviceCollectorPort }}
    protocol: UDP
  selector:
    app: {{ template "collectdexporter.fullname" . }}
    component: collectdexporter
    release: {{ .Release.Name }}
  type: ClusterIP
