{{- if .Values.grafana.persistentVolume.enabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: grafana
    release: {{ .Release.Name }}
  name: {{ template "grafana.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.grafana.persistentVolume.size | quote }}
{{- if .Values.grafana.persistentVolume.storageClass }}
{{- if (eq "-" .Values.grafana.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.grafana.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
