# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: kubestatemetrics
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}-kubestatemetrics
spec:
  ports:
    - name: http
      port: {{ .Values.kubeStateMetrics.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "prometheus.fullname" . }}
    component: kubestatemetrics
    release: {{ .Release.Name }}
  type: "NodePort"
