# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "prometheus.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "prometheus.fullname" . }}
        component: prometheus
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: configmap-reload
          image: {{ .Values.configmapReload.image.name }}:{{ .Values.configmapReload.image.tag }}
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --volume-dir=/etc/alert-rules
            - --webhook-url=http://localhost:9090/-/reload
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: rules-volume
              mountPath: /etc/alert-rules
              readOnly: true
        - name: prometheus
          image: {{ .Values.prometheus.image.name }}:{{ .Values.prometheus.image.tag }}
          imagePullPolicy: "IfNotPresent"
          args:
            - --config.file=/etc/config/prometheus.yml
            - --web.enable-lifecycle
            - --storage.tsdb.path=/var/lib/prometheus/data
            - --storage.tsdb.retention={{ .Values.prometheus.args.retention }}
          ports:
            - containerPort: 9090
          resources:
{{ toYaml .Values.prometheus.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: rules-volume
              mountPath: /etc/alert-rules
            - name: storage-volume
              mountPath: /var/lib/prometheus/data
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "prometheus.fullname" . }}
        - name: rules-volume
          configMap:
            name: {{ template "prometheus.fullname" . }}-alertrules
        - name: storage-volume
        {{- if .Values.prometheus.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "prometheus.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
