{{- if .Values.prometheus.persistentVolume.enabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.prometheus.persistentVolume.size }}"
{{- if .Values.prometheus.persistentVolume.storageClass }}
{{- if (eq "-" .Values.prometheus.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.prometheus.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
